volumes:
  node_modules:

services:
    api:
        build:
            context: ./api/
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./api:/var/www
        ports:
            - "8000:8000"
    vue:
        build:
            context: ./frontend
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        ports:
            - "3000:5173"
            - "3101:3101"
        volumes:
            - ./frontend/:/home/node/app
            - node_modules:/home/node/node_modules
        user: node
